# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    :  "air" # "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Home"
title_separator          : "-"
name                     : &name "Kulbhushan Chand"
description              : &description "Welcome to my personal website."
url                      : https://kulbhushan-chand.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "Kulbhushan-Chand/Kulbhushan-Chand.github.io" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : "/assets/images/500x300.png" # path of fallback teaser image, e.g. "/assets/images/500x300.png"
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : "staticman_v2" # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "staticman_v2" "custom"
  disqus:
    shortname            : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
staticman:
  allowedFields          : # ['name', 'email', 'url', 'message']
  branch                 : "master"
  commitMessage          : # "New comment by {fields.name}"
  filename               : # comment-{@timestamp}
  format                 : # "yml"
  moderation             : # true
  path                   : # "/_data/comments/{options.slug}" (default)
  requiredFields         : # ['name', 'email', 'message']
  transforms:
    email                : # "md5"
  generatedFields:
    date:
      type               : # "date"
      options:
        format           : # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
reCaptcha:
  siteKey                : "6LfUCm4UAAAAAC_kKxRUMp47XzUuvOvFSzo2j4oj"
  secret                 : "wUIG50npG0ICmpIjAaxd+KpXTVp1GMx7DJp0JzzkkQrpeRlm68ELVbbwYj+hK8YGr6vUwHzI7NAjhVR7R/s0Ypv+bWjwK7UxR4eokL7f+6Us+nyy96VP/b2xlR0LPLrjrp736aHaZyzlDNj07w6dN6wjw2OwweTEgs7syTwj7Fk="
atom_feed:
  path                   : # blank (default) uses feed.xml
search                   : true # true, false (default)
search_full_content      : true # true, false (default)
search_provider          : algolia # lunr (default), algolia, google
algolia:
  application_id         : NLCZAU4SPV # YOUR_APPLICATION_ID
  index_name             : my_personal_website # YOUR_INDEX_NAME
  search_only_api_key    : 11526d7bfa3cf379cfbe8d761764b33f # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : true # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification : "F4Qc7BNQPVkGnB62-j10JYgQO924mFENz7yrSvG07xE"
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing
twitter:
  username               : &twitter "ChandKulbhushan"
facebook:
  username               : &facebook "kulbhushan.chand.007"
  app_id                 :
  publisher              :
og_image                 : "/assets/images/site-logo.jpg" # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles - For Google Knowledge panel in some searches. 
    - "https://twitter.com/ChandKulbhushan"
    - "https://facebook.com/kulbhushan.chand.007"
    - "https://plus.google.com/+KulbhushanChand"
    - "https://www.linkedin.com/in/kulbhushan-chand/"
    - "https://github.com/Kulbhushan-Chand"
    - "https://www.youtube.com/user/erkulbhushan"


# Analytics
analytics:
  provider               : "google-gtag" # false (default), "google", "google-universal", "google-gtag" ,"custom"
  google:
    tracking_id          : "UA-123577698-1" #"UA-123577698-1" #"GTM-MFRMJTK"
    anonymize_ip         : # true, false (default)


# Site Author
author:
  name             : "Kulbhushan Chand"
  avatar           : "/assets/images/kulbhushan-chand.jpg" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "Autodidact"
  location         : "Jalandhar, India"
  email            :
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      #url: mailto:your.name@email.com
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "http://kulbhushan-chand.github.io/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ChandKulbhushan"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/kulbhushan.chand.007"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Kulbhushan-Chand"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"  
    - label: "Google+"
      icon: "fab fa-fw fa-google-plus-square"
      url: "https://plus.google.com/+KulbhushanChand"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/kulbhushan-chand"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/user/erkulbhushan"            
    - label: "Quora"
      icon: "fab fa-fw fa-quora"
      url: "https://www.quora.com/profile/Kulbhushan-Chand"
    - label: "Reddit"
      icon: "fab fa-fw fa-reddit"
      url: "https://www.reddit.com/user/KulbhushanChand"
    - label: "ORCID"
      icon: "orcid-icon-temp fas fa-fw fa-id-badge"
      url: "https://orcid.org/0000-0001-6502-0748"      
    - label: "OSF"
      icon: "osf-icon-temp fas fa-fw fa-snowflake"
      url: "https://osf.io/wxqdj"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Kulbhushan-Chand"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      # url:
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      # url:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url:



  #uri              : "https://kulbhushan-chand.github.io"
  #home             : # null (default), "absolute or relative url to link to author home"
  #bitbucket        :
  #codepen          :
  #dribbble         :
  #flickr           :
  #facebook         : *facebook
  #foursquare       :



  #keybase          :
  #instagram        :
  #lastfm           :
  
  #pinterest        :
  #soundcloud       :
  #stackoverflow    : # "123456/username" (the last part of your profile url, e.g. https://stackoverflow.com/users/123456/username)
  #steam            : # "steamId" (the last part of your profile url, e.g. https://steamcommunity.com/id/steamId/)
  #tumblr           :
 
  #vine             :
  #weibo            :
  #xing             :
 

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


collections:

  pages:
    output: true
    permalink: /:collection/:title/

#  posts:
#    output: true
#    permalink: /blog/:categories/:year/:month/:day/:title/


# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

# articles
  - scope:
      path: "_posts/articles"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      permalink: /blog/articles/:title/
  
    # deltaX
  - scope:
      path: "_posts/deltaX"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      permalink: /blog/deltaX/:title/

    # tutorials
  - scope:
      path: "_posts/tutorials"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      permalink: /blog/tutorials/:title/
  
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true




      
 
  

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /blog/page:num
timezone: Asia/Kolkata # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

